export const departmentData = [
  {
    id: 1,
    departmentName: "Sales", // name of the department
    image: "assets/images/Gmail-letter-N.jpg", // avatar image of the manager
    color: "#d09523", //color of the department
    manager: "Nguyen Van Quan Ly",
    email: "hrstaff@test.com", //email of manager
    numOfEmployees: 3, // number of employees
    phone: "string", // phone number of the manager
  },
  {
    id: 2,
    departmentName: "Marketing",
    image: "",
    color: "#35a975",
    manager: "",
    email: "",
    numOfEmployees: 0,
    phone: "string",
  },
  {
    id: 3,
    departmentName: "Finance",
    image: "",
    color: "#5742bd",
    manager: "",
    email: "",
    numOfEmployees: 0,
    phone: "string",
  },
  {
    id: 4,
    departmentName: "Human Resource",
    image: "",
    color: "#db322c",
    manager: "",
    email: "",
    numOfEmployees: 0,
    phone: "string",
  },
  {
    id: 5,
    departmentName: "Operations",
    image: "",
    color: "#f68d09",
    manager: "",
    email: "",
    numOfEmployees: 0,
    phone: "string",
  },
  {
    id: 6,
    departmentName: "Engineering",
    image: "",
    color: "#057d85",
    manager: "",
    email: "",
    numOfEmployees: 0,
    phone: "string",
  },
  {
    id: 7,
    departmentName: "Customer Support",
    image: "",
    color: "#81027f",
    manager: "",
    email: "",
    numOfEmployees: 0,
    phone: "string",
  },
  {
    id: 8,
    departmentName: "Research & Development",
    image: "",
    color: "#f969b5",
    manager: "",
    email: "",
    numOfEmployees: 0,
    phone: "string",
  },
  {
    id: 9,
    departmentName: "Quality Assurance",
    image: "",
    color: "#057d04",
    manager: "",
    email: "",
    numOfEmployees: 0,
    phone: "string",
  },
  {
    id: 10,
    departmentName: "Design",
    image: "",
    color: "#f90201",
    manager: "",
    email: "",
    numOfEmployees: 0,
    phone: "string",
  },
  {
    id: 11,
    departmentName: "Chăm sóc khách hàng",
    image: "",
    color: "#0003f7",
    manager: "",
    email: "",
    numOfEmployees: 0,
    phone: "string",
  },
];
